@startuml
!$pathToBase = "../../../../.."
package "[[$pathToBase/../exampleModuleFolder/example_relations.puml aaa]]" as p\$_0 #ffffff {
    package "[[$pathToBase/../exampleModuleFolder/bbb/example_relations.puml bbb]]" as p\$_1 #ffffff {
        package "[[$pathToBase/../exampleModuleFolder/bbb/ccc/example_relations.puml ccc]]" as p\$_2 #ffffff {
            package "depth_example" #00FF00 {
                class "[[$pathToBase/../sources/aaa/bbb/ccc/depth_example/BasicClass.kt BasicClass]]" as BasicClass {
                }
            }
        }
    }
}

@enduml
