@startuml
!$pathToRoot = "../../../../.."
!$pathToSourceSrcMainJava = "../../../../../../../../src/main/java"
!$pathToDocsBase = "../../../../../multi_module_example/android/example/submodule_library"
package "multi_module_example.android.example" as p\$_0 #ffffff {
    package "[[$pathToDocsBase/example_multi.puml submodule_library]]" as p\$_1 #ffffff {
        package "subpackage" as p\$_2 #00FF00 {
            interface "[[$pathToSourceSrcMainJava/multi_module_example/android/example/submodule_library/subpackage/ParameterClassB.kt ParameterClassB]]" as ParameterClassB {
            }
            interface "[[$pathToSourceSrcMainJava/multi_module_example/android/example/submodule_library/subpackage/UsageClassE.kt UsageClassE]]" as UsageClassE {
                {method} methodC
            }
        }
        package "[[$pathToDocsBase/adjacent/example_multi.puml adjacent]]" as p\$_3 #ffffff {
            interface "ParameterClassC"
            interface "UsageClassG"
        }
    }
}

ParameterClassB .up.|> ParameterClassC
UsageClassE -down-> UsageClassG
@enduml
