package multi_module_example.android.example.submodule_library.subpackage

import multi_module_example.android.example.submodule_library.adjacent.ParameterClassC

interface ParameterClassB: ParameterClassC