@startuml
!$pathToRoot = ".."
!$pathToSourceSources1 = "$pathToRoot/../sources1"
!$pathToSourceSources2 = "$pathToRoot/../sources2"
!$pathToDocsBase = "$pathToRoot/multiroot_example"
package "multiroot_example" as p\$_0 #00FF00 {
    class "[[$pathToSourceSources1/multiroot_example/BasicClass1.kt BasicClass1]]" as BasicClass1 {
    }
    class "[[$pathToSourceSources2/multiroot_example/BasicClass2.kt BasicClass2]]" as BasicClass2 {
    }
}

@enduml
